name: Build Android APK

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Install dependencies and Generate Icons
      run: |
        cd malluchat_flutter
        flutter pub get
        flutter pub run flutter_launcher_icons:main

    - name: Build APK (Release)
      run: |
        cd malluchat_flutter
        flutter build apk --release

    - name: Build AAB (Release)
      run: |
        cd malluchat_flutter
        flutter build appbundle --release

    - name: Upload APK (For direct testing)
      uses: actions/upload-artifact@v4
      with:
        name: malluchat-app-release.apk
        path: malluchat_flutter/build/app/outputs/flutter-apk/app-release.apk

    - name: Upload AAB (For Google Play Store)
      uses: actions/upload-artifact@v4
      with:
        name: malluchat-app-release.aab
        path: malluchat_flutter/build/app/outputs/bundle/release/app-release.aab
